#!/bin/bash

apt install -y htop

mkdir -p ./vegeta-i && \
    curl -L https://github.com/tsenart/vegeta/releases/download/v12.12.0/vegeta_12.12.0_linux_amd64.tar.gz | tar -xz -C ./vegeta-i && \
    mv ./vegeta-i/vegeta /usr/bin/vegeta && \
    rm -r ./vegeta-i

mkdir -p ./bat && \
    curl -L https://github.com/sharkdp/bat/releases/download/v0.25.0/bat-v0.25.0-x86_64-unknown-linux-gnu.tar.gz | tar -xz -C ./bat && \
    mv ./bat/bat-v0.25.0-x86_64-unknown-linux-gnu/bat /usr/bin/bat && \
    rm -r ./bat

mkdir -p ./lsd && \
    curl -L https://github.com/lsd-rs/lsd/releases/download/v1.1.5/lsd-v1.1.5-x86_64-unknown-linux-gnu.tar.gz | tar -xz -C ./lsd && \
    mv ./lsd/lsd-v1.1.5-x86_64-unknown-linux-gnu/lsd /usr/bin/lsd && \
    rm -r lsd

mkdir -p ./fd && \
    curl -L https://github.com/sharkdp/fd/releases/download/v10.3.0/fd-v10.3.0-x86_64-unknown-linux-gnu.tar.gz | tar -xz -C ./fd && \
    mv ./fd/fd-v10.3.0-x86_64-unknown-linux-gnu/fd /usr/bin/fd && \
    rm -r fd

mkdir -p ./delta && \
    curl -L https://github.com/dandavison/delta/releases/download/0.18.2/delta-0.18.2-x86_64-unknown-linux-gnu.tar.gz | tar -xz -C ./delta && \
    mv ./delta/delta-0.18.2-x86_64-unknown-linux-gnu/delta /usr/bin/delta && \
    rm -r delta

mkdir -p ./fzf && \
    curl -L https://github.com/junegunn/fzf/releases/download/v0.65.2/fzf-0.65.2-linux_amd64.tar.gz | tar -xz -C ./fzf && \
    mv ./fzf/fzf /usr/bin/fzf && \
    rm -r fzf

mkdir -p ./lazygit && \
    curl -L https://github.com/jesseduffield/lazygit/releases/download/v0.55.0/lazygit_0.55.0_linux_x86_64.tar.gz | tar -xz -C ./lazygit && \
    mv ./lazygit/lazygit /usr/bin/lazygit && \
    rm -r lazygit

curl -L https://github.com/BurntSushi/ripgrep/releases/download/14.1.1/ripgrep_14.1.1-1_amd64.deb -o rg.deb && \
    dpkg -i rg.deb && \
    rm -r rg.deb

curl -L https://github.com/ajeetdsouza/zoxide/releases/download/v0.9.8/zoxide_0.9.8-1_amd64.deb -o zoxide.deb && \
    dpkg -i zoxide.deb && \
    rm zoxide.deb

curl -L https://github.com/jqlang/jq/releases/download/jq-1.8.1/jq-linux-amd64 -o /usr/bin/jq

curl -L https://github.com/mikefarah/yq/releases/download/v4.47.2/yq_linux_amd64 -o /usr/bin/yq
